version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev # as using compose on dev mode for live reload
      target: builder
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
    # environment:
    # - PORT=7860
    command: air
